package com.njh.common.core;

/**
 * @author niejiahuan
 */
public interface ReqTag {
    /**
     * 登录
     */
    String REQ_TAG_POST_SIGNIN = "post_signin";

    String REQ_TAG_GET_HOME_MOMENT_SELECTED_FLAG = "REQ_TAG_GET_HOME_MOMENT_SELECTED_FLAG";
    String REQ_TAG_GET_HOME_MOMENT_LIST = "REQ_TAG_GET_HOME_MOMENT_LIST";
    String REQ_TAG_GET_HOME_ACTIVITY_ACTIVITY_LIST = "REQ_TAG_GET_HOME_ACTIVITY_ACTIVITY_LIST";
    String REQ_TAG_GET_HOME_ACTIVITY_PREVIEWS_LIST = "REQ_TAG_GET_HOME_ACTIVITY_PREVIEWS_LIST";
    String REQ_TAG_GET_HOME_MOMENT_MEMBER_SEARCH = "REQ_TAG_GET_HOME_MOMENT_MEMBER_SEARCH";
    String REQ_TAG_POST_HOME_MOMENT_PUBLISH = "REQ_TAG_POST_HOME_MOMENT_PUBLISH";
    String REQ_TAG_POST_HOME_MOMENT_FOLLOW = "REQ_TAG_POST_HOME_MOMENT_FOLLOW";
    String REQ_TAG_POST_HOME_ACTIVITY_ACTIVITY_ZAN = "REQ_TAG_POST_HOME_ACTIVITY_ACTIVITY_ZAN";
    String REQ_TAG_POST_HOME_ACTIVITY_PREVIEWS_ZAN = "REQ_TAG_POST_HOME_ACTIVITY_PREVIEWS_ZAN";

    interface Service {
        // v1/service/dealers
        String SERVICE_DEALERS = "SERVICE_DEALERS";
        // v1/service/package
        String SERVICE_PACKAGE = "SERVICE_PACKAGE";
    }

}
